name: Deploy existing Docker Hub image to Azure Web App - miappwebG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'miappwebG'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PUBLISHPROFILE_BBBBFFFA55714269992EE7B08053809B }}
        images: 'crisn28cr/miappflask:latest'
