name: Deploy existing Docker Hub image to Azure Web App - miappwebD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'miappwebD'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c21f68a1f87431ebde1b8ff1b4cec20 }}
        images: 'crisn28cr/miapp-flask-mysql:latest'
